export type ExamAndLeaguePages =
  | "Home"
  | "Exams"
  | "Leagues"
  | "MyExams"
  | "Contents"
  | "ErrorPage"
  | "MyLeagues"
  | "StartExam"
  | "ExamDetails"
  | "LeagueDetails"
  | "ExamCompleted"
  | "ExamInstructions"
  | "Wallet"
  | "Settings"
  | "ExamCorrection"
  | "MyResults";
