export type ExamAndCoursePages =
  | "Home"
  | "Exams"
  | "Courses"
  | "MyExams"
  | "Contents"
  | "ErrorPage"
  | "MyCourses"
  | "StartExam"
  | "ExamDetails"
  | "CourseDetails"
  | "ExamCompleted"
  | "ExamInstructions"
  | "Wallet"
  | "Settings"
  | "ExamCorrection"
  | "MyResults";
