export type ExamAndPublicationPages =
  | "Home"
  | "Exams"
  | "Library"
  | "BookDetails"
  | "MyExams"
  | "ErrorPage"
  | "MyPublications"
  | "StartExam"
  | "ExamDetails"
  | "ExamCompleted"
  | "ExamInstructions"
  | "Wallet"
  | "Settings"
  | "ExamCorrection"
  | "Document"
  | "MyResults";
